name: Build

on: [push, pull_request]

jobs:
  Build-apk-for-android:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Cloning modlaucher repo and preparing for building
      run: |
        git clone https://github.com/DMK95/Srceng-mod-launcher/
        sudo apt-get update
        sudo apt-get install -f -y openjdk-8-jre zip apksigner
    - name: Build Android (32 bit)
      run: |
        scripts/build-android-armv7a.sh
    - name: Build Android (64 bit)
      run: |
        scripts/build-android-aarch64.sh    
    - name: Build APK
      run: |
        scripts/build-apk.sh 
    - name: Rename APK
      run: |
         mv Srceng-mod-launcher/build/android/mod-signed.apk clientmod-release.apk

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: clientmod-apk
        path: clientmod-release.apk
